# Generated by Django 3.2 on 2022-01-25 21:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Saison',
                'verbose_name_plural': 'Saisons',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transporte',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=512)),
                ('day', models.CharField(choices=[('Montag', 'Montag'), ('Dienstag', 'Dienstag'), ('Mittwoch', 'Mittwoch'), ('Donnerstag', 'Donnerstag'), ('Freitag', 'Freitag'), ('Samstag', 'Samstag'), ('Sonntag', 'Sonntag')], max_length=10)),
                ('date', models.DateField()),
                ('ca_makeup', models.BooleanField(default=False)),
                ('makeup', models.TimeField(blank=True, null=True)),
                ('warehouse', models.TimeField(blank=True, null=True)),
                ('sun', models.TimeField(blank=True, null=True)),
                ('gathering', models.TimeField()),
                ('ca_play', models.BooleanField(default=False)),
                ('play', models.TimeField()),
                ('trailer', models.CharField(blank=True, max_length=256, null=True)),
                ('information', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('fix', models.BooleanField(default=True)),
                ('cert', models.IntegerField(blank=True, choices=[(0, '2G+'), (1, '2G'), (2, '3G')], default=None, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.category')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.season')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.transport')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('-date', 'play'),
            },
        ),
    ]
