# Generated by Django 3.2.9 on 2021-11-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('sort', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
    ]
