# Generated by Django 3.2.9 on 2021-11-02 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211102_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort',), 'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
        migrations.CreateModel(
            name='Evening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Montag', 'Montag'), ('Dienstag', 'Dienstag'), ('Mittwoch', 'Mittwoch'), ('Donnerstag', 'Donnerstag'), ('Freitag', 'Freitag'), ('Samstag', 'Samstag'), ('Sonntag', 'Sonntag')], max_length=10)),
                ('date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.category')),
            ],
            options={
                'verbose_name': 'Abend',
                'verbose_name_plural': 'Abende',
                'ordering': ('-date',),
            },
        ),
    ]
