# Generated by Django 3.2.12 on 2022-04-19 08:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220126_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date', 'sort'), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterField(
            model_name='event',
            name='cert',
            field=models.IntegerField(blank=True, choices=[(0, '2G+'), (1, '2G'), (2, '3G'), (3, '3G+')], default=None, null=True),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=1024)),
                ('from_date', models.DateField()),
                ('until_date', models.DateField(blank=True, null=True)),
                ('from_time', models.TimeField(verbose_name='From')),
                ('until_time', models.TimeField(blank=True, null=True, verbose_name='Until')),
                ('description', models.TextField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.season')),
            ],
            options={
                'verbose_name': 'Kalender',
                'verbose_name_plural': 'Kalender',
            },
        ),
    ]
