# Generated by Django 3.2.9 on 2021-11-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211102_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transporte',
            },
        ),
    ]
