# Generated by Django 4.2.7 on 2023-11-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_tourcalendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourcalendar",
            name="from_dt",
            field=models.DateTimeField(blank=True, null=True, verbose_name="From"),
        ),
        migrations.AddField(
            model_name="tourcalendar",
            name="to_dt",
            field=models.DateTimeField(blank=True, null=True, verbose_name="To"),
        ),
    ]
