# Generated by Django 4.2.7 on 2023-11-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_tourcalendar_from_dt_tourcalendar_to_dt"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourcalendar",
            name="reset_period",
            field=models.BooleanField(default=False),
        ),
    ]
