# Generated by Django 3.2.9 on 2021-11-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211102_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='makeup',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
