# Generated by Django 4.2.7 on 2023-11-09 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_tourcalendar_reset_period"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tourcalendar",
            options={
                "ordering": ("category",),
                "verbose_name": "Tour Kalender",
                "verbose_name_plural": "Tour Kalender",
            },
        ),
        migrations.AddField(
            model_name="tourcalendar",
            name="season",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.season"
            ),
            preserve_default=False,
        ),
    ]
