# Generated by Django 4.2.7 on 2023-11-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_tourcalendar_options_tourcalendar_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourcalendar",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
