# Generated by Django 4.2.7 on 2023-11-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_tourcalendar_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourcalendar",
            name="reset_name",
            field=models.BooleanField(default=False),
        ),
    ]
