# Generated by Django 4.2.7 on 2023-11-10 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_tourcalendar_reset_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tourcalendar",
            options={
                "ordering": ("category",),
                "verbose_name": "Tour Kalender Feed",
                "verbose_name_plural": "Tour Kalender Feed",
            },
        ),
        migrations.AlterField(
            model_name="tourcalendar",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.season",
            ),
        ),
    ]
