# Generated by Django 4.2.7 on 2023-11-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_tourcalendar_options_alter_tourcalendar_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourcalendar",
            name="sort",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
