# Generated by Django 4.2.7 on 2023-11-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_tourcalendar_sort"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourcalendar",
            name="fetch_events",
            field=models.BooleanField(default=True),
        ),
    ]
