# Generated by Django 5.1.2 on 2024-10-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_tourcalendar_fetch_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gathering',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
