# Generated by Django 5.1.2 on 2025-02-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_alter_event_gathering"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="departure_home",
            field=models.TimeField(blank=True, null=True, verbose_name="Abfahrt Car"),
        ),
    ]
