# Generated by Django 5.1.2 on 2025-02-12 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_event_departure_home"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="date_end",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="departure_home",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Abfahrt Car nach Windisch"
            ),
        ),
    ]
