# Generated by Django 5.2.7 on 2025-11-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_event_city_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(0, 'Auftritt'), (1, 'Infos'), (2, 'GV'), (3, 'Anderes')], default=0, verbose_name='Art'),
        ),
    ]
